defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:current

    steps:
      - checkout

      - run:
          name: Versions
          command: |
            npm --versions
            node -v
            git version

      - run:
          name: NPM install
          command: |
            npm install

      - run:
          name: Make
          command: |
            make

      - run:
          name: Package
          command: |
            make source-package

      - run:
          name: Install AWS cli
          command: |
            if [[ $CIRCLE_PULL_REQUESTS ]]; then exit 0; fi;

            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.6-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.6 get-pip.py --user
            export PATH=~/.local/bin:$PATH
            pip install awscli --upgrade --user

      - run:
          name: Publish
          command: |
            if [[ $CIRCLE_PULL_REQUESTS ]]; then exit 0; fi;

            export PATH=~/.local/bin:$PATH

            aws s3 cp build/ s3://src-jitsi.rocket.chat/ --recursive
            aws s3 cp --content-type "application/json" ios/apple-app-site-association s3://src-jitsi.rocket.chat/apple-app-site-association

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
